# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            原文网——高质量信息分享
tagline:          ''
description:      '高质量信息分享网站'
url:              www.yuanwen.wang

paginate:      10

# Custom vars
version:          0.0.3

# Comments

comments :
    provider : duoshuo
    duoshuo :
          short_name : codeliu2016


